config/routes.rb
JqMobile::Application.routes.draw do
  resources :todos

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates_presence_of :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :set_layout
  before_filter :set_iphone_format

  def set_iphone_format
    request.format = :iphone if iphone_request?
  end
  
  def set_layout
    iphone_request? ? "iphone" : "application"
  end
  
  private
  
  def iphone_request?
    request.user_agent =~ /(Mobile.+Safari)/
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
    @data_url = todos_path
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = Todo.find(params[:id])
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(params[:todo])
      if @todo.save
        redirect_to todos_url, notice: 'Todo was successfully created.'
      else
        render action: "new"
     end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])

    if @todo.update_attributes(params[:todo])
      redirect_to "/todos/", notice: 'Todo was successfully updated.' 
    else
      render action: "edit"
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JqMobile</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/iphone.iphone.erb
<html>
<head>
  <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>iPhone</title>
  <%= stylesheet_link_tag    "mobile_application" %>
  <%= javascript_include_tag "mobile_application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div data-role="page">

  <%= yield %>

  </div>
</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :due %><br />
    <%= f.date_select :due %>
  </div>
  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_form.iphone.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain">
    <%= f.label :due %>
    <%= f.text_field :due, "data-role"=>"datebox", "data-options"=>'{"mode": "flipbox"}' %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :task %>
    <%= f.text_field :task %>
  </div>
  <div class="actions">
    <button type="submit" data-theme="b">更新</button>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/edit.iphone.erb
<div data-role="header">
  <%= link_to 'Back', todo_path(@todo), "data-icon"=>"arrow-l" %>
  <h1>Todoの変更</h1>
  <%= link_to 'Delete', todo_path(@todo), :confirm => "#{@todo.task} を削除してよいですか?", :method => :delete, "data-icon"=>"delete" %>
</div>

<div data-role="content">
  <%= render 'form' %>
</div>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>Due</th>
    <th>Task</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.due %></td>
    <td><%= todo.task %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/index.iphone.erb
    <div data-role="header">
      <h1>Listing todos</h1>
      <%= link_to 'Add', new_todo_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
    </div>

    <div data-role="content">
      <ul data-role="listview">
      <% @todos.each do |todo| %>
        <li data-role="list-divider" style="padding: 0.1em 15px;"><%= todo.due %></li>
        <li><%= link_to todo.task ,todo %></li>
      <% end %>
      </ul>
    </div>
  </div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/new.iphone.erb
<div data-role="header">
  <%= link_to 'Back', todos_path, "data-icon"=>"arrow-l" %>
  <h1>新規Todo</h1>
</div>

<div data-role="content">
  <%= render 'form' %>
</div>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Due:</b>
  <%= @todo.due %>
</p>

<p>
  <b>Task:</b>
  <%= @todo.task %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/todos/show.iphone.erb
<div data-role="header">
  <%= link_to 'Back', todos_path, "data-icon"=>"arrow-l" %>
  <h1>Todo詳細</h1>
  <%= link_to 'Edit', edit_todo_path(@todo), "data-icon"=>"check" %> 
</div>

<div data-role="content">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Due:</b>
    <%= @todo.due %>
  </p>

  <p>
    <b>Task:</b>
    <%= @todo.task %>
  </p>
</div>